### ISSUE TITLE
Bug i think

### ISSUE THREAD

**Issue by meaningg** [xxCoderforlife/Simple-Drugs#15]
![image](https://user-images.githubusercontent.com/61989272/135442123-697afcd7-8bcf-49f6-bf12-93716a81598d.png)
When click on air with empty hand

**Comment by xxCoderforlife** [comment]
What build version are you using?

**Comment by xxCoderforlife** [comment]
This is fixed in the "Build 147".
https://github.com/xxCoderforlife/Simple-Drugs/releases/tag/v2.7-dev%2Bbuild147

**Comment by meaningg** [comment]
TY!
