### ISSUE TITLE
Error when clicking on an empty slot

### ISSUE THREAD

**Issue by Xen0Xys** [xxCoderforlife/Simple-Drugs#38]
**Describe the bug**
I got an error in console when i made a click in my inventory in an empty slot

**To Reproduce**
1. Open inventory
2. Click on an empty slot
3. See the error in console

**Expected behavior**
No errors in console

**Screenshots**
![image](https://user-images.githubusercontent.com/47594493/153193779-8cd64d59-d640-40c7-915e-9ef26dc9ce55.png)

- 2.7.3 DEV
- Paper: git-Paper-187

**Comment by SpaceXElaborator** [comment]
I believe issue was fixed. Please get back and reop of the issue persists. I cannot seem to replicate error

Potential Fixed with: https://github.com/xxCoderforlife/Simple-Drugs/commit/2070ea591a984eb46bcc12ed768a9761065c9840
