### ISSUE TITLE
Can't use drugs

### ISSUE THREAD

**Issue by Xen0Xys** [xxCoderforlife/Simple-Drugs#40]
**Describe the bug**
I cannot use drugs, event if I have the permission to use it (drugs.use.*)
I also can't get drugs from the bag of drugs (click but don't get anything)

**To Reproduce**
1. Craft a drug
2. Right click with it in hand
3. Nothing append

1. Open bag of drugs
2. Left click on the wanted drug
3. Nothing append

**Expected behavior**
Get effects of the drugs and get the drugs from bag of drugs

- 2.7.3 DEV
- Paper: git-Paper-187

**Comment by xxCoderforlife** [comment]
Fixed.
